#!/bin/bash 
shotnum=249
nr=126 #$4
nt=2048 #$5
prefix=$1
  for((this_shot=0; this_shot < ${shotnum}; this_shot++))
  do 
    tar=${prefix}${this_shot}
    tarname=${tar}.bin
    echo "in=${tarname} n1=2048 n2=126 data_format=native_float" > tmp.rsf

    sftransp < tmp.rsf plane=12 |
      sfput o1=500 d1=20 label1=Depth unit1=m o2=0 d2=0.002 label2=Time unit2=s |
      sftransp plane=12 > show.rsf
    
    sfgrey < show.rsf wanttitle=n screenratio=1.4 screenht=10 \
      labelsz=6 font=2 titlesz=6 pclip=97 pad=n scalebar=y > ${tar}.vpl
    
    vpconvert `pwd`/${tar}.vpl color=y fat=2 serifs=y format=eps
    sfrm show.rsf
    rm tmp.rsf ${tar}.vpl
    #gv ${tar}.eps
  done

